### PR TITLE
Tweak somewhat confusing variable name

### LINKED ISSUE #92: M2 not FedFunds
In your example use of 

federal_funds_series <- fredr_series_search_text(
    search_text = "federal funds",
    order_by = "popularity",
    sort_order = "desc",
    limit = 1
)

popular_funds_series <- federal_funds_series$id

you end up with M2 not FedFunds

### PR DESCRIPTION
**Pull request by DavisVaughan**
Closes #92

### CODE REVIEW

**Comment by DavisVaughan** [comment]
@sboysel would you like me to initiate a fredr CRAN release?

**Review by sboysel — APPROVED** [review]

**Comment by sboysel** [comment]
Yes a new CRAN release seems appropriate.  Is the recommended tool these days `devtools::release()` or are you submitting manually?  Thanks!

**Comment by DavisVaughan** [comment]
You could start with `usethis::use_release_issue(version = "2.0.1")`, which gives you a nice checklist of things to do.

Do you want to do it, or should I?

**Comment by sboysel** [comment]
Why don't you take care of this one (I will monitor email) and I can take care of them after this time.  Not have a GitHub PAT and I'm not 100% on what `usethis::use_release_issue()` is doing under the hood.

**Pull request merged**
