### PR TITLE
Feature/function parameters

### PR DESCRIPTION
**Pull request by DavisVaughan**
- I've pulled in your most recent changes

- `fredr_series_observations()` is ready to go

- `fredr_tags()` is ready to go

- `fredr_search()` is a bit of a mess at the moment as I haven't had time to update from my last commit. I think we should probably split each endpoint into separate help docs as well since each will have its own nuances with the params. Autocomplete should make them easy to find.

### CODE REVIEW

**Comment by DavisVaughan** [comment]
A few notes:

* Each function help page includes a link to the relevant docs page

* Params will be implemented in the order that the API specifies, except for `fredr_series_observations()` which I imagine will be the most popular function, where I have pulled the most common and useful params to the front.

* For required params, validate them using a `validate_param_name()` function directly inside the function that they belong to (for example, see `validate_series_id()` in `fredr_series_observations().

*  For optional params, pass all of them to `capture_args()` which will validate them, modify them if necessary (turns dates into formatted characters, limit is forced to be an integer, etc), and return a named list of them (using some rlang fun)

* `capture_args()` is set up so that we can write all validation for all endpoints here. The nice thing is that our args default to `NULL`, and if you have a list and you try to do `lst$doesntexist` then you still get `NULL` back. This means we can try and validate something like `observation_start` even when we are calling something like `fredr_tags()` and have no problem, because `args$observation_start` will just return NULL.

* With the above in mind, make sure your validation functions always check for `NULL` and just return the value as is if it is `NULL`, see `validate_limit()`.

* `validate_is_class()` is a nice meta-helper for checking for class (`Date` or `character` is what is has been used for so far) and returning nice error messages.

* `rlang` has been added as an import. It already came with `tibble` so there is no extra overhead.

* `do.call()` is now how you call `fredr::fredr()` from each function. This is so we can pass our endpoint specific args + the user args all together.

**Comment by DavisVaughan** [comment]
Side note, are you using RStudio? I noticed you have a Makefile and that has overriden my shortcuts for building, reloading, and documenting the R package. Its not a big deal, just wondered if you had this there for a definite reason, also not sure if me manually changing from using the Makefile to using "package" building tools in RStudio (and keeping your Makefile) would affect anything if you happen to not use RStudio

**Comment by sboysel** [comment]
This is great work.  Thanks @DavisVaughan!

- I'll follow your approach when implementing new functions.  I can start on the search functions in the Series endpoint.  I will rename `fredr_search()` in your PR to `fredr_search_text()` and modify the remaining search functions to use your approach.  Once `fredr_series_observations()` and the Series search functions jive with with rest of the package, I'll merge this feature branch into master and we can start iterating on this framework.
- I don't think it's too excessive to have a separate file and documentation page for each endpoint function.
- Validation and argument capture look great.  Will be easy to extend these functions down the line.

**Comment by DavisVaughan** [comment]
* for `fredr_series_search_text()` and `fredr_series_search_id()` shouldn't we just use `fredr_series_search()` and let the user specify the `search_type`? https://research.stlouisfed.org/docs/api/fred/series_search.html#search_type

* Should we go ahead and merge what we have now? It includes the base for the validation stuff (necessary for other endpoints) so then you can immediately start work on the rest of the series pieces and I can work on the rest of the tags endpoint and the sources endpoint.

**Comment by sboysel** [comment]
- If there are only 2 options for `search_type`, I think reduce ambiguity for the user `fredr_series_search_text()` and `fredr_series_search_id()`.
- I wanted to set the current functions with the new approach before merging.  I've pushed them to your branch in f20f510 and will merge once all CI checks complete.  After this, we can start working in feature branches in main fredr repo.

**Comment by DavisVaughan** [comment]
Makes sense!!

**Comment by sboysel** [comment]
The failed checks have to do with Travis removing encrypted environment variables for PRs.  I'll merge from a branch pushed to the main repo for now.

**Pull request closed without merging**
